---
- name: Enable or disable termination protection of an instance by its ID
  amazon.aws.ec2_instance:
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    instance_ids:
      - '{{ instance_id }}'
    termination_protection: '{{ termination_protection }}'
    region: ap-southeast-1