---
- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Change state of an instance by its ID
      amazon.aws.ec2_instance:
        state: '{{ state }}'
        instance_ids:
          - '{{ instance_id }}'
        aws_access_key: '{{ ec2_access_key }}'
        aws_secret_key: '{{ ec2_secret_key }}'
        region: ap-southeast-1