---
- hosts: localhost
  gather_facts: no
  vars:
    instance_name: '{{ instance_name }}'
    key_name: 'BizKit'
    region: ap-southeast-1
    image: '{{ ami_id }}'
    instance_type: '{{ instance_type }}'
    sec_group: '{{ instance_abbr }}-{{ environment_abbr }}'
    instance_environment: '{{ instance_environment }}'
    environment_abbr: '{{ environment_abbr }}'
    ports: '{{ ports }}'
    vpc_id: '{{ vpc_id }}'
    subnet_1: '{{ subnet_1_id }}'
    subnet_2: '{{ subnet_2_id }}'
  roles:
    - role: deploy_ec2