---
- hosts: localhost
  gather_facts: no
  vars:
    instance_name: '{{ instance_name }}'
    region: ap-southeast-1
    instance_type: '{{ instance_type }}'
    sec_group: '{{ instance_abbr }}-db'
    storage_size: '{{ storage_size }}'
    backup_retention_period: '{{ backup_retention_period }}'
    db_password: '{{ db_password }}'
    max_allocated_storage: '{{ max_storage }}'
    backup_window: '{{ backup_window }}' # hh24:mi-hh24:mi
    maintenance_window: '{{ maintenance_window }}' # ddd:hh24:mi-ddd:hh24:mi
    vpc_id: '{{ vpc_id }}'
    subnet_1: '{{ subnet_1_id }}'
    subnet_2: '{{ subnet_2_id }}'
  roles:
    - role: deploy_rds