---
- name: Release elastic IP address
  amazon.aws.ec2_eip:
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    device_id: '{{ instance_id }}'
    ip: '{{ ip_address }}'
    state: 'absent'
    release_on_disassociation: true
    region: ap-southeast-1

- name: Terminate an instance by its ID
  amazon.aws.ec2_instance:
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    instance_ids:
      - '{{ instance_id }}'
    state: 'absent'
    region: ap-southeast-1

- name: Delete security group
  amazon.aws.ec2_security_group:
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    group_id: '{{ security_group }}'
    state: 'absent'
    region: ap-southeast-1
