---
- name: Create security group
  amazon.aws.ec2_security_group:
    name: '{{ sec_group }}'
    description: '{{ instance_name }} {{ environment_abbr }} settings'
    region: '{{ region }}'
    vpc_id: '{{ vpc_id }}'
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: '{{ ports }}'
        cidr_ip: 0.0.0.0/0
    tags:
      Name: '{{ instance_name }} {{ instance_environment }}'
      Environment: '{{ instance_environment }}'
      Project: '{{ instance_name }}'
      FrappePress: Yes
  register: ec2_sec_group

- name: Provision an EC2 instance
  amazon.aws.ec2_instance:
    name: '{{ instance_name }} {{ instance_environment }}'
    vpc_subnet_id: '{{ subnet_1_id }}'
    instance_type: '{{ instance_type }}'
    security_group: '{{ ec2_sec_group.group_id }}'
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    region: '{{ region }}'
    wait: true
    state: started
    launch_template:
      name: BizKitFrappePress
    network_interfaces:
      - assign_public_ip: false
        subnet_id: '{{ subnet_1_id }}'
        groups:
          - '{{ ec2_sec_group.group_id }}'
    tags:
      Environment: '{{ instance_environment }}'
      Project: '{{ instance_name }}'
      FrappePress: Yes
      EmailAccountSecretARN: arn:aws:secretsmanager:ap-southeast-1:024113903379:secret:EMAIL-ACCOUNT-PASSWORDS-wpNZm3
  register: ec2

- name: Allocate a new elastic IP and associate it with the EC2 instance
  amazon.aws.ec2_eip:
    device_id: '{{ ec2.instance_ids[0] }}'
    in_vpc: true
    region: '{{ region }}'
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    tags:
      Environment: '{{ instance_environment }}'
      Project: '{{ instance_name }}'
      FrappePress: Yes

- name: Get instance facts
  amazon.aws.ec2_instance_info:
    aws_access_key: '{{ ec2_access_key }}'
    aws_secret_key: '{{ ec2_secret_key }}'
    region: '{{ region }}'
    instance_ids:
      - '{{ ec2.instance_ids[0] }}'
  register: result